@host=http://localhost:8080

GET {{host}}/products

###
GET {{host}}/products/4

###

POST {{host}}/products
Content-Type: application/json

{
    "name":"test6"
    
}

###
PUT {{host}}/products/6
Content-Type: application/json

{
    "name":"test5",
    "price": 0
}